### ISSUE TITLE
Consider not recommending ventoy anymore

### ISSUE THREAD

**Issue by RoyalOughtness** [castrojo/bluefin-website#33]
I love Ventoy but unfortunately there are numerous valid and serious concerns about it. I know uBlue cares about supply chain security so I figured I would call this out since it was brought to my attention, in case uBlue folks felt the same way after learning more. If not feel free to just close this.

They are storing blobs of foss software in a GPL repo (instead of installing dependencies as part of an automated build process) which is not only a supply chain security nightmare but potentially illegal as far as I understand (not a lawyer) given [this ruling](https://news.ycombinator.com/item?id=31399580#:~:text=Court%20Ruling%20shows%20the%20GPL,and%20contractual%20agreement%20%7C%20Hacker%20News&text=The%20specific%20difference%20here%20seems,of%20the%20specific%20GPL%20code.) that the GPL is both a license and a contract 

https://github.com/ventoy/Ventoy/issues/2795 
https://github.com/secureblue/secureblue/issues/515

**Comment by castrojo** [comment]
I fixed docs last night so that's all set too, thanks!
