### ISSUE TITLE
image selector bug with -latest stream

### ISSUE THREAD

**Issue by inffy** [castrojo/bluefin-website#46]
Just a tiny issue on the image selector. I haven't noticed the latest stream to be available previously but seems it is now, but the selector text shows just a code tag:

![2024-11-16-105023_hyprshot](https://github.com/user-attachments/assets/4d8595c9-d48b-465e-9340-ec499070479a)

**Comment by castrojo** [comment]
Latest shouldn't be in the chooser at all, just gts and stable.

**Comment by tulilirockz** [comment]
Fixed with #48
