### ISSUE TITLE
File name in checksum file does not match ISO file name

### ISSUE THREAD

**Issue by joestrouth1** [castrojo/bluefin-website#54]
The Bluefin docs link to the [Silverblue installation instructions](https://docs.fedoraproject.org/en-US/fedora-silverblue/installation/). In the section labeled "Preparing Boot Media", that page links to [instructions for using Fedora Media Writer](https://docs.fedoraproject.org/en-US/fedora/latest/preparing-boot-media/#sect-verifying-images).

Those instructions did not work for me. I'm a developer with an Asus laptop and an Nvidia GPU running windows.

The website[1] linked me to:
- `bluefin-dx-asus-nvidia-latest.iso`
- `bluefin-dx-asus-nvidia-latest.iso-CHECKSUM`

The checksum file:
```
9c1bbeb225c0333c1e145fd9f751c485a539c9696cb5bfdf4458286e3905536b  bluefin-dx-hwe-nvidia-latest.iso
```

The difference between `dx-hwe-nvidia` and `dx-asus-nvidia` contributes to an error when the docs instruct Windows users to string match the name of the ISO.
```
> $image = "bluefin-dx-asus-nvidia-latest.iso"
> $checksum_file = "bluefin-dx-asus-nvidia-latest.iso-CHECKSUM"
> $sha256 = New-Object -TypeName System.Security.Cryptography.sha256CryptoServiceProvider
> $expected_checksum = ((Get-Content $checksum_file | Select-String -Pattern $image) -split " ")[0].ToLower()
```
The error is not very helpful.
```
You cannot call a method on a null-valued expression.
At line:1 char:1
```

The checksums match it's just a bit rough. 

---

1. I first encountered this when downloading Aurora and found it was the same on Bluefin

**Comment by castrojo** [comment]
cc @m2Giles I think this is because we added the hwe images but didn't update the website?

**Comment by m2Giles** [comment]
They were renames.

The checksum files need the filename to be updated.

But the hwe image = Asus image = surface image.
